Viết chương trình với các yêu cầu sau :
1. Tạo arr_ zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.

In [1]:
import numpy as np
arr_zeros=np.zeros(5,dtype=int)
arr_zeros[4]=1
print(arr_zeros)

[0 0 0 0 1]


2. Tạo arr h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của art _h.

In [2]:
arr_h=np.arange(10,25)
print(arr_h[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


3. Cho arr _k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 01), tạo art _1 từ art _k với các phần tử khác 0.

In [3]:
arr_k=np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_l=np.array([i for i in arr_k if i!=0])
print(arr_l)

[1 2 8 2 1 3 5]


4. Từ arr_1 của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.

In [4]:
arr_4=np.append(arr_l,10)
arr_4=np.append(arr_4,20)
print(arr_4)

[ 1  2  8  2  1  3  5 10 20]


5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.

In [5]:
arr_5=np.insert(arr_4,5,100)
print(arr_5)

[  1   2   8   2   1 100   3   5  10  20]


6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

In [6]:
arr_6=np.delete(arr_5,[0,1,2])
print(arr_6)

[  2   1 100   3   5  10  20]
