Thao tác trên mảng nhiều chiều :
Viết chương trình thực hiện các yêu cầu sau :
1. Tạo array arr có kích thước 3x3 với các giá trị True

In [1]:
import numpy as np
arr = np.full((3,3),True,dtype= bool)
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape((3,3))
print('arr kích thước 3x3',arr_2D)

arr kích thước 3x3 [[0 1 2]
 [3 4 5]
 [6 7 8]]


2. Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ arr_ ID, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.

In [2]:
column1 = list(arr_2D[:,0])
arr_2D[:,0] = arr_2D[:,2]
arr_2D[:,2] = column1
print('chuyển cột 1 sang cột 3 và ngược lại:',arr_2D)

chuyển cột 1 sang cột 3 và ngược lại: [[2 1 0]
 [5 4 3]
 [8 7 6]]


3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.

In [3]:
row1 = list(arr_2D[0,:])
arr_2D[0,:] = arr_2D[1,:]
arr_2D[1,:] = row1
print('chuyển dòng 1 sang dòng 2 và ngược lại:',arr_2D)

chuyển dòng 1 sang dòng 2 và ngược lại: [[5 4 3]
 [2 1 0]
 [8 7 6]]


4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.

In [4]:
arr_2D = arr_2D[::-1,::1]
print('đảo ngược các dòng của arr_2D:',arr_2D)

đảo ngược các dòng của arr_2D: [[8 7 6]
 [2 1 0]
 [5 4 3]]


5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.

In [5]:
arr_2D = arr_2D[::1,::-1]
print('đảo ngược các cột của arr_2D',arr_2D)


đảo ngược các cột của arr_2D [[6 7 8]
 [0 1 2]
 [3 4 5]]


6. Cho arr_ 2D_null = np.array([[1, 2, 3], [np.NaN, 5, 61, [7, np.NaN, 9], [4, 5, 6]]),
Kiểm tra trong array có giá trị rống không?

In [6]:
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
if np.isnan(arr_2D_null).any() :
    print('có giá trị rỗng')
else:
    print('không có giá trị rỗng')

có giá trị rỗng


7. Từ arr_2D_ null của câu 6, thay thế giá trị null bằng 0.

In [7]:
arr_2D_no_null = np.nan_to_num(arr_2D_null)
print('sau khi thay thế',arr_2D_no_null)

sau khi thay thế [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
